[package]
name = "cartographer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = "0.5" # make sure this is the latest version
bevy_ecs_tilemap = "0.4.0"
log = "0.4"